version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 885067822627.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t docker .
      - docker tag docker 885067822627.dkr.ecr.ap-south-1.amazonaws.com/dockerrepo
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 885067822627.dkr.ecr.ap-south-1.amazonaws.com/dockerrepo

